### ISSUE TITLE
Cannot connect to ml-pipeline service

### ISSUE THREAD

**Issue by aloysius-lim** [canonical/kfp-operators#6]
Connecting to ml-pipeline Service from Jupyter (running in the same cluster) fails, with "connection refused". 

Turns out that the selector for ml-pipeline was not working, and so the Service was not pointing to any valid endpoints. This is confirmed in Azure Portal, where the Kubeflow cluster is deployed:

![Screenshot 2021-05-04 at 5 02 38 PM](https://user-images.githubusercontent.com/3433970/116981851-a8e03700-acfa-11eb-9aa0-03442ed1c70a.png)

Editing the YAML file for the ml-pipeline Service seems to work around the issue temporarily:

```yaml
spec:
  selector:
    # juju-app: kfp-api (Remove this and replace with the following)
    app.kubernetes.io/name: kfp-api
```

After applying the change, the connection to ml-pipeline Service from Jupyter works.

But this is only a temporary workaround, as the YAML configuration reverts to the default (with "juju-app" as the key) after a few minutes.
