### ISSUE TITLE
Use `get_charms_build_with_cache.yaml` on pull request workflow

### ISSUE THREAD

**Issue by DnPlas** [canonical/kfp-operators#641]
### Context

https://github.com/canonical/charmed-kubeflow-workflows/pull/88 introduces a reusable workflow that allows the CI to build charms in their dedicated machines and with charmcraft cache enabled. These enablements improve the build time and ensure that the same charm artefact is tested individually, as a bundle, and published.

### What needs to get done

1. Add the canonical/charmed-kubeflow-workflows/.github/workflows/get_charms_build_with_cache.yaml workflow on pull request workflow

```yaml
name: On Pull Request

# On pull_request, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# * always run builds with cache
on:
  pull_request:

jobs:
  get-paths-and-build:
    name: Get charm paths and build with cache
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/get_charms_build_with_cache.yaml@main

  tests:
    name: Run Tests
    needs: [get-paths-and-build]
    uses: ./.github/workflows/integrate.yaml
    secrets: inherit

  # publish runs in parallel with tests, as we always publish in this situation
  publish-charm:
    name: Publish Charm
    needs: [get-paths-and-build]
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
```

### Definition of Done

The pull request workflow uses canonical/charmed-kubeflow-workflows/.github/workflows/get_charms_build_with_cache.yaml before proceeding on the publish and test jobs.
